/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: James.Moore (https://sketchfab.com/James.Moore)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/8c419f6d0cbc4580a2e2b9d273969b97
title: Wooden Bowl
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useBox, usePlane } from '@react-three/cannon'


type GLTFResult = GLTF & {
  nodes: {
    BowlA_Wood_0: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
  }
}

export default function DiceModel({ ...props }: JSX.IntrinsicElements['group']) {
  const [group, api] = usePlane(() => ({}))
  const { nodes, materials } = useGLTF('/3d/bowl/scene.gltf') as GLTFResult
  console.log(nodes.BowlA_Wood_0)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.25, 0.06, 0.6]} rotation={[-Math.PI / 2, 0, 0]} scale={[80.11, 80.11, 80.11]}>
            <mesh geometry={nodes.BowlA_Wood_0.geometry} material={materials.Wood} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/bowl/scene.gltf')
